---
## tasks to install and setup tomcat

- name: install tomcat
  yum:
    name: "{{ package_name }}"
    state: latest


- name: enable  tomcat
  service:
    name: "{{ package_name }}"
    enabled: yes
  notify: restart apache

- name:  create tomcat default web directory
  file:
    path: "{{tomcat_base_dir}}"
    state: directory


- name: copy static index.html to tomcat
  template:
    src: index.html.j2
    dest: "{{ tomcat_base_dir }}/index.html"
    mode: 0644
  notify: restart apache

#handlers:
#- name: restart apache
#  service:
#    name: "{{ package_name }}"
#    state: restarted

